### ISSUE TITLE
Upgrade to TailwindCSS v3.0

### ISSUE THREAD

**Issue by gupta-ji6** [scriptified/scriptified.dev#87]
Let's upgrade Scriptified to TailwindCSS v3.0 just after it's launched, because why not!

## References

1. [Upgrade Guide](https://tailwindcss.com/docs/upgrade-guide)
2. [Tailwind CSS v3.0 Announcement](https://tailwindcss.com/blog/tailwindcss-v3)

**Comment by gupta-ji6** [comment]
@hussamkhatib let us know if you interested in picking this up :)

**Comment by hussamkhatib** [comment]
Hi, sure I would like to pick this up.
